spring:
  application:
    name: turbine
server:
  port: 8989
management:
  port: 8990
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
turbine:
  app-config: ribbon-consumer
  cluster-name-expression: new String('default')
  combine-host-port: true