server:
  port: 8081
spring:
  application:
    name: HELLO-SERVICE
  zipkin:
      base-url: http://localhost:9411
  sleuth:
      sampler:
        percentage: 1
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
logging:
  level:
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: DEBUG

