server:
  port: 9001
spring:
  application:
    name: feign-consumer
  zipkin:
    base-url: http://localhost:9411
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
logging:
  level:
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: DEBUG

