server:
  port: 7001
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/luijia2006/spring-cloud/
          searchPaths: config-repo
          username: luijia2006
          password: mama620326
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/